import React, {useEffect, useRef, useState} from 'react';
import {House, PanelsTopLeft, ChartNoAxesCombined, ListTree, UserRound, Settings2, CircleHelp, PanelLeftClose, ArrowRight, X, LogOut, Play} from 'lucide-react';
import logo from './approved-logo.png';
import './dashboard.css';
import './dashboard-app.css';

const pages = ['Home','Docks','Earnings','Activity','Profile','Settings','Help'] as const;
const symbols = [House,PanelsTopLeft,ChartNoAxesCombined,ListTree,UserRound,Settings2,CircleHelp];
const docks = [{id:'image',name:'Image ad dock'},{id:'question',name:'Quick question dock'},{id:'survey',name:'Survey dock'},{id:'video',name:'Video dock'}];
type Page = typeof pages[number];
function Chart() {
  const [range,setRange]=useState('30D');
  const [hover,setHover]=useState<number|null>(null);
  const box=useRef<HTMLDivElement>(null);
  const [width,setWidth]=useState(600);
  useEffect(()=>{const observer=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));if(box.current)observer.observe(box.current);return ()=>observer.disconnect();},[]);
  const left=57,right=18,base=151,end=Math.max(left+40,width-right);
  const days=range==='7D'?7:range==='30D'?30:range==='90D'?90:1;
  const date=(fraction:number)=>{const d=new Date();d.setDate(d.getDate()-Math.round((1-fraction)*(days-1)));return d.toLocaleDateString(undefined,{month:'short',day:'numeric'});};
  return <section className="panel chart-panel"><div className="chart-head"><div className="chart-title"><h2>Earnings</h2><p>{range==='All'?'All time':`Last ${days} days`} · $0.00</p></div><div className="range-group" role="group" aria-label="Chart range">{['7D','30D','90D','All'].map(r=><button key={r} className={`range-button ${r===range?'is-active':''}`} aria-pressed={r===range} onClick={()=>{setRange(r);setHover(null);}}>{r}</button>)}</div></div><div ref={box} className="chart-wrap"><svg className="chart" viewBox={`0 0 ${width} 190`} role="img" aria-label="Earnings in US dollars, currently zero"><title>Earnings in USD</title>{[0.03,0.02,0.01,0].map((n,i)=><g key={n}><line className="grid" x1={left} x2={end} y1={16+i*45} y2={16+i*45}/><text x={left-10} y={20+i*45} textAnchor="end">${n.toFixed(2)}</text></g>)}<path className="line" d={`M${left} ${base}H${end}`}/>{[0,.5,1].map(f=><text key={f} x={left+(end-left)*f} y={181} textAnchor={f===0?'start':f===1?'end':'middle'}>{range==='All'?(f===0?'Start':f===1?'Today':''):date(f)}</text>)}{hover!==null&&<g><line className="guide" x1={left+(end-left)*hover} x2={left+(end-left)*hover} y1={16} y2={base}/><circle className="point" cx={left+(end-left)*hover} cy={base} r={4}/></g>}<rect className="chart-hit" x={left} y={16} width={end-left} height={135} onPointerMove={e=>{const rect=e.currentTarget.ownerSVGElement!.getBoundingClientRect();setHover(Math.max(0,Math.min(1,((e.clientX-rect.left)*width/rect.width-left)/(end-left))));}} onPointerLeave={()=>setHover(null)}/></svg>{hover!==null&&<div className="chart-tooltip" style={{left:Math.max(60,Math.min(width-60,left+(end-left)*hover)),top:140}}><span>{date(hover)}</span><strong>$0.00</strong></div>}</div></section>;
}
function Dock({kind}:{kind:string}) {
 const [answer,setAnswer]=useState('');
 return <div className="live-dock" aria-label={`${kind} dock preview`}><div className="dock-art" aria-hidden="true">{kind==='video'&&<Play size={28}/>}</div><div className="dock-copy"><span className="sponsored">Sponsored · Example</span><strong>{kind==='video'?'A new perspective.':kind==='question'?'Mountains or beaches?':kind==='survey'?'What interests you?':'Find your next favorite.'}</strong>{kind==='question'||kind==='survey'?<button className="dock-cta" onClick={()=>setAnswer('Answer selected')}>{answer|| (kind==='question'?'Mountains':'Technology')}</button>:<span className="dock-cta">{kind==='video'?'Video format preview':'Explore'}</span>}</div></div>;
}
export function Dashboard({onSignOut}:{onSignOut:()=>void}) {
 const [page,setPage]=useState<Page>('Home'),[collapsed,setCollapsed]=useState(false),[running,setRunning]=useState<string|null>('image'),[confirm,setConfirm]=useState(false),[menu,setMenu]=useState(false),[activity,setActivity]=useState<string[]>([]);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(confirm)dialog.current?.showModal();else dialog.current?.close();},[confirm]);
 function run(id:string|null){setActivity(a=>[`${id?`Started ${docks.find(d=>d.id===id)?.name}`:'Closed running dock'} · ${new Date().toLocaleTimeString()}`,...a]);setRunning(id);}
 return <div id="aod-dashboard-preview" className={collapsed?'collapsed':''}><div className="window"><aside className="sidebar" aria-label="Application navigation"><div className="brand-row"><div className="dashboard-logo-frame"><img className="logo" src={logo} alt="Ads on Demand"/></div><button className="collapse" aria-label={collapsed?'Expand sidebar':'Collapse sidebar'} aria-expanded={!collapsed} onClick={()=>setCollapsed(!collapsed)}><PanelLeftClose size={17}/></button></div><nav className="nav">{pages.map((p,i)=>{const Icon=symbols[i];return <button key={p} className={`nav-button ${page===p?'is-active':''}`} title={p} aria-label={p} aria-current={page===p?'page':undefined} onClick={()=>setPage(p)}><Icon size={18}/><span className="nav-label">{p}</span></button>;})}</nav><div className="sidebar-bottom"><div className="device"><span className="online-dot"/><span>This PC · Local session</span></div><button className="profile-button" aria-label="Account menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}><span className="avatar">J</span><span className="profile-copy"><strong>Personal account</strong><span>Free plan</span></span></button>{menu&&<div className="profile-menu"><button className="menu-button" onClick={onSignOut}><LogOut size={16}/>Sign out</button></div>}</div></aside><section className="main"><header className="topbar"><div className="page-heading"><strong>{page}</strong><span>Your desktop at a glance</span></div><button className="close-button" disabled={!running} onClick={()=>setConfirm(true)}><X size={16}/>Close all</button></header><main className="content">
 {page==='Home'?<><section className="home-intro"><h1>Welcome back.</h1><p>See your earnings and manage what is running on your desktop.</p></section><div className="overview"><section className="panel balance-panel"><div className="panel-label">Available earnings</div><div className="balance-row"><div className="balance-number">$0.00</div><div className="today">Earned today<strong>$0.00</strong></div></div><div className="balance-note">Only verified earnings will be shown here.</div><button className="primary-button" onClick={()=>setPage('Earnings')}>View analytics <ArrowRight size={16}/></button></section><section className="panel docks-panel"><div className="panel-heading"><div><h2>Dock status</h2><p>This PC · Display 1</p></div><span className={`status ${running?'running':'stopped'}`}>{running?'Running':'Stopped'}</span></div><div className="desktop-preview">{running?<Dock key={running} kind={running}/>:<div className="no-dock">No dock running</div>}</div><div className="dock-footer"><button className="secondary-button" onClick={()=>setPage('Docks')}>Manage docks <ArrowRight size={16}/></button><span className="coming-soon">Multiple running docks with Plus · Coming soon</span></div></section><Chart/></div></>:page==='Docks'?<><section className="home-intro"><h1>Docks</h1><p>Save your favorites. Run one dock at a time.</p></section><div className="saved-list">{docks.map(d=><section className="saved-dock" key={d.id}><div><strong>{d.name}</strong><span className={running===d.id?'running':'stopped'}>{running===d.id?'Running':'Stopped'}</span></div><button className={running===d.id?'close-button':'primary-button'} onClick={()=>run(running===d.id?null:d.id)}>{running===d.id?'Stop':'Start'}</button></section>)}</div><p className="dashboard-note">Starting another dock stops the current one. These controls demonstrate the layouts inside the app; desktop overlay windows are coming next.</p></>:page==='Earnings'?<><section className="home-intro"><h1>Your earnings</h1><p>Available $0.00 · Today $0.00</p></section><Chart/></>:page==='Activity'?<><section className="home-intro"><h1>Activity</h1></section>{activity.length?<ul className="activity-list">{activity.map((a,i)=><li key={i}>{a}</li>)}</ul>:<p className="dashboard-note">Your dock changes will appear here.</p>}</>:<section className="placeholder"><div className="placeholder-inner"><h1>{page}</h1><p>{page==='Profile'?'Account and interest preferences will be available when account services are connected.':page==='Settings'?'More appearance and device controls are coming soon. Use the sidebar button to collapse navigation.':'This preview works locally. You can explore your dashboard and dock formats without an account. Real sign-in and desktop docks are coming next.'}</p><button className="secondary-button" onClick={()=>setPage('Home')}>Back to Home</button></div></section>}
 </main></section></div><dialog className="confirm-dialog" ref={dialog} onCancel={()=>setConfirm(false)}><h2>Close the running dock?</h2><p>Your setup stays saved. Start it again from Docks.</p><div className="dialog-actions"><button className="secondary-button" autoFocus onClick={()=>setConfirm(false)}>Cancel</button><button className="close-button" onClick={()=>{run(null);setConfirm(false);}}>Close dock</button></div></dialog></div>;
}
